package member;

import java.io.Serializable;

/**
 * 회원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Member implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private String id;

	/** password. */
	private String password;

	/** hp. */
	private String hp;

	/** email. */
	private String email;

	/** address. */
	private String address;

	/** pic. */
	private String pic;

	/**
	 * 생성자.
	 */
	public Member() {
	}

	/**
	 * id을 설정합니다..
	 * 
	 * @param id
	 *            id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * id을 가져옵니다..
	 * 
	 * @return id
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * password을 설정합니다..
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * password을 가져옵니다..
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * hp을 설정합니다..
	 * 
	 * @param hp
	 *            hp
	 */
	public void setHp(String hp) {
		this.hp = hp;
	}

	/**
	 * hp을 가져옵니다..
	 * 
	 * @return hp
	 */
	public String getHp() {
		return this.hp;
	}

	/**
	 * email을 설정합니다..
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * email을 가져옵니다..
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * address을 설정합니다..
	 * 
	 * @param address
	 *            address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * address을 가져옵니다..
	 * 
	 * @return address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * pic을 설정합니다..
	 * 
	 * @param pic
	 *            pic
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * pic을 가져옵니다..
	 * 
	 * @return pic
	 */
	public String getPic() {
		return this.pic;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Member other = (Member) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
